services:
  postgres:
    image: postgres:18-alpine
    container_name: delivery_postgres
    environment:
      POSTGRES_DB: delivery_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    ports:
      - "5432:5432"
    networks:
      - delivery_net

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    container_name: delivery_auth_service
    environment:
      PORT: 3001
      DATABASE_URL: postgresql://user:password@postgres:5432/delivery_db
      JWT_ACCESS_SECRET: your_super_secret_access_key_here
      JWT_REFRESH_SECRET: your_super_secret_refresh_key_here
      NODE_ENV: production
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - delivery_net

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: delivery_frontend
    ports:
      - "80:80"
    depends_on:
      - auth-service
    networks:
      - delivery_net

networks:
  delivery_net:
    driver: bridge

volumes:
  postgres_data:
